namespace Shared.Localisation;

public static class LanguageName
{
    public const string TopBarRectangle                 = "topBar:rectangle";
    public const string TopBarEllipse                   = "topBar:ellipse";
    public const string TopBarTriangle                  = "topBar:triangle";
    public const string TopBarSave                      = "topBar:save";
    public const string TopBarOpen                      = "topBar:open";
    public const string ConsoleBarExecute               = "consoleBar:execute";
    public const string ConsoleBarClearErrors           = "consoleBar:clearErrors";
    public const string ErrorExpectedArgs               = "error:expectedArgs";
    public const string ErrorOr                         = "error:or";
    public const string ErrorTypeInferrenceCtor         = "error:typeInferrenceCtor";
    public const string ErrorTypeInferrenceArgs         = "error:typeInferrenceArgs";
    public const string ErrorOutsideRange               = "error:outsideRange";
    public const string TankLiteVariableDoesntExist     = "tankLite:variableDoesntExist";
    public const string TankLiteClassDoesntExist        = "tankLite:classDoesntExist";
    public const string TankLiteVariableNotFunction     = "tankLite:variableNotFunction";
    public const string TankLiteVariableIsReadonly      = "tankLite:variableIsReadonly";
    public const string TankLiteVarTypeInterferrence    = "tankLite:variableTypeInterferrence";
    public const string TankLiteVariableIsNotObject     = "tankLite:variableIsNotObject";
    public const string TankLiteCannotAdd               = "tankLite:cannotAdd";
    public const string TankLiteCannotSubtract          = "tankLite:cannotSubtract";
    public const string TankLiteCannotMultiply          = "tankLite:cannotMultiply";
    public const string TankLiteCannotDivide            = "tankLite:cannotDivide";
    public const string TankLiteCannotOperate           = "tankLite:cannotOperate";
    public const string TLNameRectangle                 = "tlName:rectangle";
    public const string TLNameTriangle                  = "tlName:triangle";
    public const string TLNameEllipse                   = "tlName:ellipse";
    public const string TLNameConstructor               = "tlName:constructor";
    public const string TLNameType                      = "tlName:type";
    public const string TLNameXPos                      = "tlName:xPos";
    public const string TLNameYPos                      = "tlName:yPos";
    public const string TLNameWidth                     = "tlName:width";
    public const string TLNameHeight                    = "tlName:height";
    public const string TLNameRotation                  = "tlName:rotation";
    public const string TLNameColor                     = "tlName:color";
    public const string TLNameRed                       = "tlName:red";
    public const string TLNameGreen                     = "tlName:green";
    public const string TLNameBlue                      = "tlName:blue";
    public const string TLNameAlpha                     = "tlName:alpha";
    public const string TLNameInt                       = "tlName:int";
    public const string TLNameObject                    = "tlName:object";
    public const string TLNameFunc                      = "tlName:func";
    public const string TLNameSetPosition               = "tlName:setPosition";
    public const string TLNameSetSize                   = "tlName:setSize";
    public const string TLNameSetColor                  = "tlName:setColor";
    public const string TLNameSetRotation               = "tlName:setRotation";
    public const string TLNameMove                      = "tlName:move";
    public const string UiNoFileSelected                = "ui:noFileSelected";
}